### ISSUE TITLE
Add CloudFormation template for pycon.cz domain

### ISSUE THREAD

**Issue by tricoder42** [pyvec/cz.pycon.org-2015#14]
As mentioned in #13, we should keep configuration of infrastructure in repository too, so we can reproduce it anytime using automation tool like Ansible or SaltStack.

At this point, http://pycon.cz should redirect to official http://cz.pycon.org. We can achieve it on AWS using S3 bucket and Route53 hosted zone:
1. S3
   1. Create pycon.cz bucket which redirects to http://cz.pycon.org
2. Route53
   1. Create hosted zone pycon.cz
   2. Add A record as an alias for pycon.cz S3 bucket

**Comment by pixelfields** [comment]
@tricoder42 I have a time to work on it tomorrow during a day. Is it ok? Or do you want write the CF template by yourself using https://github.com/cloudtools/troposphere  as mentioned in #13 ?

**Comment by tricoder42** [comment]
@pixelfields Feel free to work on it, I'll appreciate any help with that.

Edit: Sorry, I mess up the issue numbers :) Please do it in this issue, troposphere comment belongs to here.

**Comment by tricoder42** [comment]
By the way, don't use `troposphere` if you don't want to. It's just suggestion. How do you usually write templates? By hand or do you use AWS templates?

**Comment by pixelfields** [comment]
@tricoder42 Always by hand. What do you mean "use AWS templates"?

**Comment by tricoder42** [comment]
AWS has some "preconfigured" templates. But do it your way :)

**Comment by tricoder42** [comment]
@pixelfields I would appreciate your help with setup of IAM users.

I created a draft of Ansible playbook and CloudFormation template in #15. I would like to have one superuser-like user, which can manage only resources associated with this project. All other users (PyCon contributors) will have access only to resources required for deployment (EC2, S3 or EB).

I want to give contributors as much privileges as possible, but I don't want to expose my whole AWS account.

**Comment by pixelfields** [comment]
@tricoder42 I suppose that the best way is filtering resources by a tag. Each resource belonging to this project will be mandatory tagged by "project" key with "cz-pycon-2015" value. Then you can create the policy with the condition and assign the action only to resources with this tag. 

I have created a CF template to create corresponding policy and roles. See: #17 . Feel free to modify and/or test it as I'm focusing on deploying ec2 and db clusters and I'm not very strong in the AWS identity management.

**Comment by pixelfields** [comment]
@tricoder42 I just pushed Cloud Formation templates as you requested. First one creates the S3 bucket with website configuration, second then deploys Hosted Zone and creates A record for given domain as an alias to the bucket created by the previous template. See #18 .
I tested these stacks in "eu-west-1" region, so if you will create stacks in the different region, please be sure to refer to the right S3 bucket hosted zone ID when creating the hosted zone for domain. For list of zone IDs please see this page: http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region

**Comment by tricoder42** [comment]
Fixed in `feature/aws-cli`, will be merged in master soon.
