### ISSUE TITLE
Date

### ISSUE THREAD

**Issue by encukou** [pyvec/cz.pycon.org-2015#22]
November 21-22 is bold in the README. Is that final? It's actually not Pycon-free, see http://2015.es.pycon.org/en/

Mikey suggests going for the week after Django Under The Hood, so that overseas speakers might extend their trip to visit us. (And go to Spain the week after that.)

**Comment by tricoder42** [comment]
It's not final. Final it will be after we find out venue and book it.

Week before sounds good! Let's change it.

**Comment by calmrat** [comment]
"http://www.djangounderthehood.com/ ... [will start on] 5th of November (Thursday) and end late on the 7th of November. It will take place in Amsterdam, the Netherlands at the Pakhuis de Zwijger."

Assuming the event will be two days and start exactly a week after, the current proposal is November (thur->fri) 13-14, or 3 days, (thur->sat) 12-14? 

Or, as is done with DevConf in Brno, Fri-Sun seems to work well too. So, that would mean Fri Nov 14 - Sun Nov 16.

**Comment by calmrat** [comment]
Oh, i see in the README. Looks pretty clear it's going to be 2 days. (sorry, i'm just catching up on the details here)

```
Possible dates
See calendar at http://www.pycon.org for "PyCon free" weekends.
14-15/11/2015 - only one week after Django Under the Hood
21-22/11/2015
28-29/11/2015
december -- too late, too cold?
```

Could someone explain if there are some rules to abide by according to pycon.org? I mean, are the dates available for this event limited according to the pycon free weekends schedule? Or is the idea just to avoid overlap if at all possible?

**Comment by encukou** [comment]
We just want to avoid overlap. (And, if possible, position the event so that overseas people can extend their existing trip to Europe to visit us.)

**Comment by tricoder42** [comment]
The date is 13-15 November

The schedule should be:
Friday 13th: Django Girls workshop
Saturday 14th: PyCon - talks
Sunday 15th: PyCon - workshops and/or sprints

**Comment by calmrat** [comment]
Well, other than the fact DjangoGirls will have to manage their luck carefully on Friday 13 (https://en.wikipedia.org/wiki/Friday_the_13th) ;) I personally have no objections to those dates. Only other Pycon events on those dates are in the US according to the calendar. 

And just FYI: http://lanyrd.com/2015/nov/?page=13
Nov 7-9 Open Alt in Brno
Nov 13 - Open Development Camp in the Hague
Nov 14-16 - Open Con in Brussels
Nov 16-18 - Global Scrum Gathering in Prague
