### ISSUE TITLE
Create "Visit Brno" page

### ISSUE THREAD

**Issue by thatdocslady** [pyvec/cz.pycon.org-2015#29]
Sections:
- Introduction / general text
- Traveling to Brno
- Transportation in Brno
- Places to stay
- Places to eat
- Practical information (money, credit cards)

**Comment by tricoder42** [comment]
This task is already on Trello board https://trello.com/c/eDJck9Bx/3-travel-information

**Comment by rkuska** [comment]
http://www.use-it.travel/cities/detail/brno/ this may come handy for visitors in Brno (map with cool places to visit by locals)
