### ISSUE TITLE
Create Team page

### ISSUE THREAD

**Issue by thatdocslady** [pyvec/cz.pycon.org-2015#30]
Static page with the information from the gist: https://gist.github.com/tricoder42/529b6c1cfd2bd6952fb6

**Comment by honzajavorek** [comment]
Please let me know once it's up and running, I'd like to promote it so our supporters know to who they can turn in case they want to offer some hand. Also, it will be more concrete for the community to see real people behind it. I want them to be sure that the conference is coming from the existing structures, backed by Pyvec, etc. and it's not some random standalone effort.

**Comment by thatdocslady** [comment]
@honzajavorek there are still quite a few fixes to make to the website before we can launch and start promoting, stay tuned to the #website channel on Slack ;-)

**Comment by honzajavorek** [comment]
@thatdocslady sure!

I'm trying to be careful with promoting the site, I don't want to route people to unfinished stuff as that's missed opportunity. That's why I don't like the FB event already exists etc. :-| I've put warnings everywhere that the info isn't final at least.
