### ISSUE TITLE
Pre-release Review Issues

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/cz.pycon.org-2015#39]
### Content Issues
- [x] I am missing links/badges promoting FB event page and Twitter account on the website. There could be even a GitHub link/badge leading to this repository. I will also need Lanyrd icon once I create the event there.
- [ ] We should have a placeholder male and female silhouette pictures we could use for speakers we want to announce but from which we did not get photo yet. There are missing speakers in the speakers sections - more than one is already confirmed AFAIK.
- [x] Sponsorship page features name "PyCon Czech Republic", which is not consistent with the rest of the page and promoting, where we refer to the conference as "PyCon CZ".
- [x] Team page titles are not consistent in (title) casing ("Swag & collectables" vs. "Tickets & Mentoring").
- [x] Team page does not feature Petr Viktorin who's responsible for sprints/workshops.
- [x] I'd prefer to have a photo instead of an avatar on team page. Feel free to take [the one from DG page](https://djangogirls.org/uploads/event/coaches/ja.jpg) or I can send you the original photo.
- [x] There is no conference email (`info@pycon.cz` or something) people could use to ask us questions or contact us. That's quite bad message to people on many levels.
- [x] At the bottom of the Team page I would love to see following call-to-action area with a button: "Wanna become part of our team or just offer a hand? Join us at our Slack channel!" The button would lead to `mailto:info@pycon.cz?subject=Please, add me to your Slack!` Optionally also: "Wanna support us? Spread the word, follow our Twitter/Facebook and share our announcements!" Again, with links and stuff.
### Design Glitches
- [x] Favicon leads to unixstickers website and it does not feature our current logo. (addressed in https://github.com/pyvec/cz.pycon.org-2015/pull/41)
- [x] Logo is embedded as PNG instead of SVG with PNG fallback (or without fallback, any modern browser can handle SVG), so it looks awful on retina display.
- [x] The grey stripe with "claim/subtitle/welcome" sentence could be red with white bold text. I think it could make the welcome page more vivid. (The same applies to the stripe at the bottom of http://cz.pycon.org/sponsorship.html )
- [x] Dots in the schedule could be in blue and red logo colors.
- [x] Vertical margins between sections and headings seem to be very inconsistent. Some parts are too close to each other, some are too far away.
- [x] _Brno, Czech Republic_ and _November 14-15, 2015_ should be probably larger relative to how large the logo is.
- [x] Label text floating over the map has shadow - that looks very strange on such a flat site. The only other thing having shadow are schedule bubbles, but they look more natural (even though I would remove the shadow also there, personally).
- [x] Footer could use more padding.
- [x] On Mac/Firefox, I see horizontal scrollbars on the team page.
- [x] "Wanna get on stage?" section could be probably just centered. Left-aligned looks strange in the context of the whole page. Similarly for the other paragraph sections, but this one quite stands out.
### Technical Issues
- [x] When using permalink to a section, e.g. `http://cz.pycon.org/#section-sponsors`, heading of the section is hidden under the upper toolbar.

---

Otherwise it's great! :tada: :checkered_flag:

**Comment by tricoder42** [comment]
Most of changes are ready for review at dev.pycon.cz. Please be gentle...

**Comment by honzajavorek** [comment]
- [x] I cannot see the social icons except for GitHub (Mac/Firefox):
  
  <img width="272" alt="screen shot 2015-09-03 at 08 27 45" src="https://cloud.githubusercontent.com/assets/283441/9651823/bda45e00-5215-11e5-8fa5-d910e69d2b82.png">
  
  Seems to work in Chrome.
  
  **Update:** Caused by [AdBlock](https://adblockplus.org/forum/viewtopic.php?f=2&t=25444&p=108036#p107940).

**Comment by honzajavorek** [comment]
I love change of the subtitle font to the Amatic!

**Comment by honzajavorek** [comment]
- [x] Just realized the menu item "Contact" should be "Venue". Contact is misleading. Moreover, if Contact won't be present in menu, people will look for the contact in the footer, which is the place where contact actually is. (addressed in https://github.com/pyvec/cz.pycon.org-2015/pull/41)

**Comment by tricoder42** [comment]
I guess we can close this one, most of these issues are already merged and published.

**Comment by honzajavorek** [comment]
:+1:
