### ISSUE TITLE
Persistent URLs?

### ISSUE THREAD

**Issue by encukou** [pyvec/cz.pycon.org-2015#44]
It looks like all pages on the current website will be deleted or moved before next year.

Should we have "2015" in all URLs, and set up appropriate redirects, to prevent broken links/bookmarks?

**Comment by tricoder42** [comment]
We can create 2015.cz.pycon.org and setup redirect from cz.pycon.org

**Comment by honzajavorek** [comment]
Other conferences usually move the old web to subdomain or prefix it with
year (cz.pycon.org/2015/...) and create a new one in the root. Permalinks
are not so valuable once the conference is over. Root of the site should
always point to the latest site.

H

**Comment by encukou** [comment]
> Other conferences usually move the old web to subdomain or prefix it with year (cz.pycon.org/2015/...) and create a new one in the root. 

What other conferences do you mean? us.pycon.org , europython.eu , and djangocon.eu all redirect to permanent URLs.

> Permalinks are not so valuable once the conference is over. 

What makes them not valuable? When I blog about PyCon CZ 2015, I want to be able to link to it.

> Root of the site should always point to the latest site.

Yes.

**Comment by tomasbedrich** [comment]
I would prefer http://cz.pycon.org/2015/whatever and redirecting http://cz.pycon.org/whatever always to the latest year.

**Comment by tricoder42** [comment]
@tomasbedrich Why so? The advantage of <year>.cz.pycon.org format is that each year can be hosted on different server (or moved to some archive, after the conference ends). cz.pycon.org/<year>/ is less flexible, as it would require the same hosting solution for every edition.

**Comment by tricoder42** [comment]
There's no standard way, as far as I can see, so it might be a matter of personal preference:

Subdomain format:
http://djangocon.us
http://djangocon.eu
http://europython.eu/

Subfolder format:
http://us.pycon.org

Are there any known technical issues or advantages/disadvantages of both solutions?

**Comment by tomasbedrich** [comment]
@tricoder42 The subdomain format is fine for 2nd level domains. >3 levels looks confusing for me.

**Comment by honzajavorek** [comment]
I also don't find 2015.cz.pycon.org very appealing, visually.

In case the pages are going to be more or less static when the conference is over, you can always "freeze" them into static pages and serve them archived this way into a sub-folder and serve by any server technology.

**Comment by tricoder42** [comment]
Yes, but organizers of upcoming years must be aware, that with website conference, they must also serve whole archive of PyCon CZ.

The subdomain solution is DNS-based, so only administrator of DNS records of pycon.cz / cz.pycon.org must be aware that archive is located somewhere.

I don't care about visual appearance though. It's true, that sub-sub-domain isn't very standard.

**Comment by tomasbedrich** [comment]
I don't see any benefit in DNS-based solution. Still either DNS admin or website admin will have to take care of this.

**Comment by hroncok** [comment]
> Yes, but organizers of upcoming years must be aware

You act like it will once be someone else :)

**Comment by tricoder42** [comment]
Of course, I don't expect that I will organize all upcoming PyCon CZ :) It's a community event. Next year it might be in different place (Prague), organized by different people. Why not?

**Comment by encukou** [comment]
I don't think awareness is a problem. If the next pages are on cz.pycon.org/2016, it should be clear that there should be an archive at /2015.

**Comment by hroncok** [comment]
@tricoder42 I didn't mean the same people, I mean it's going to be pyvec, isn't it?

**Comment by tricoder42** [comment]
@hroncok Most probably yes, but I don't know :)

At the moment I'm trying to figure out how to setup redirects to subfolders in AWS S3, which is our current hosting solution. I know how to setup domain redirects, but could find any info about redirects within the same domain...

**Comment by honzajavorek** [comment]
You are too nice to the next organizers :D

**Comment by tomasbedrich** [comment]
@tricoder42 just use .htaccess

**Comment by tricoder42** [comment]
@tomasbedrich I really don't think that AWS S3 supports .htaccess. Could you please point me to docs?

Right now I'm more inclined to subdomain format. Yesterday I tried to move all content to subfolder and setup redirect, but it's a bit messy. I've uploaded WIP to `year-folder` branch, so anybody can work on it. It's a static website, so it needs to be checked by hand that all absolute URL point to subfolder...

**Comment by tomasbedrich** [comment]
@tricoder42 I can't, I have no experience with AWS S3. But you are right
that it doesn't support .htaccess, at least according to StackOverflow. So
sorry for my pointless advice...

**Comment by tricoder42** [comment]
Will be solved as part of #59. S3 can't handle redirects to subfolders very well. Moreover, I want to add SSL to site and that's impossible with S3. Have to setup Cloudfront, which doesn't work... too complicated :)
