### ISSUE TITLE
Choose T-shirt design

### ISSUE THREAD

**Issue by Naomak** [pyvec/cz.pycon.org-2015#58]
Here are some suggestions for front/back side of t-shirts.
Do you feel like there should be some more information? Do you like the city (Brno) to be there? Do you have any special desire?

Please, comment and vote!

![triko_front_all](https://cloud.githubusercontent.com/assets/809507/10142627/1d26e692-6614-11e5-8cb8-b1ad2f5def26.png)
![triko_back_all](https://cloud.githubusercontent.com/assets/809507/10142632/23824cca-6614-11e5-8567-d3e6e941f08d.png)

**Comment by calmrat** [comment]
Very nice.

Vote on what i see:
Front: 5
Back: 1/2 - I can't "spot the difference" b/w 1/2

The snake wrap around is cute and creative. Not sure it's for everyone, but
I like it, for sure. I also, for whatever reason, think it would be cool if
the snake actually wrapped entirely around the shirt/waist somehow, where
on the front you see some stripes and on the back you clearly see it's a
snake.

Other ideas: lion badge and wording (eg, 5 but smaller and with brno
even?) could be like a polo shirt with pycon CZ 2015 brno small on the
front side on the front top left breast

The back could be just the snake since those words are already once on the
front.

PyCon CZ 2015 Brno should be somewhere on the shirt, at least once, I would
think.

Should each or some be written only once to avoid being redundant? Or
written twice? I would think once is enough.

Just a few thoughts. Cheers

-Chris

**Comment by netman92** [comment]
front 4, back 6

**Comment by tricoder42** [comment]
Back -- either 4 or 6. I would choose 6, if I had only one choice. I really _love_ the snake theme :+1: :snake: 

Front -- neither :) I don't like that front/back versions have the same (similar) wording -- PyCon CZ 2015. What about use PyCon CZ small logo at the position of heart? Without any words.

Another variation: Snake without text on the backside and 2 on the frontside?

**Comment by netman92** [comment]
@tricoder42 I really like this:

> What about use PyCon CZ small logo at the position of heart? Without any words.

:+1: :100:

**Comment by Naomak** [comment]
@kejbaly2 The difference in 1/2 is only size:)

About the text on front/back side - I would not definitely repeat it too. Only choose what and where.

How looks tricoder's idea + classic middle-chest-ironman-engine style:
![triko_front_06-7](https://cloud.githubusercontent.com/assets/809507/10148791/e0170396-6635-11e5-96cb-b489fae47f50.png)

**Comment by tricoder42** [comment]
Ironman engine!!! :)

I vote for: Front 2, Back 6 without text

**Comment by honzakral** [comment]
Love the designs! Could we perhaps choose a different color of the t-shirt? I would prefer something more exciting than white...

**Comment by tricoder42** [comment]
@HonzaKral I agree. We're a bit limited by logo colors -- we either have to design logo for dark background or choose very bright color for t-shirt, like gray, pale blue, etc.

**Comment by strx** [comment]
front 5, back 1/2

**Comment by Naomak** [comment]
@HonzaKral From my point of view, the white choice was to stick with web color theme plus of course best background for multicolour hand-drawned theme of this year.

**Comment by encukou** [comment]
My vote: Front 5 (the later one, with the small logo); back 1/2.

**Comment by veruu** [comment]
I like all the front sides (including the 5 and 6 posted later) and the idea of snake wrap is awesome, however it'd look better if it was wrapped around the whole T-shirt. It still looks great even if it's only on the back side, so my vote for the back is 4 and 6.

**Comment by Naomak** [comment]
Ok guys. Final voting for the winner. And dont say just I like all. Make your choice.
![final](https://cloud.githubusercontent.com/assets/809507/10370997/a10a954c-6de1-11e5-8e36-dc767c01a15b.png)

**Comment by encukou** [comment]
front: 1
back: 2

**Comment by jaroslav-kubicek** [comment]
front: 1)
back: 2)

**Comment by starenka** [comment]
Front 1, back 1 (the lurking snake)

**Comment by tricoder42** [comment]
2, 1

**Comment by netman92** [comment]
1,1

**Comment by Naomak** [comment]
F: 2
B: 1

**Comment by veruu** [comment]
1, 1

**Comment by honzajavorek** [comment]
F1, B2

**Comment by Debosque** [comment]
1,2

**Comment by calmrat** [comment]
F: 1
B: 2

**Comment by pixelfields** [comment]
F1, B2

**Comment by VerosK** [comment]
iff I'm allowed to vote - F1, B1.

**Comment by hroncok** [comment]
1 1

**Comment by deshipu** [comment]
2 1

**Comment by TomasTomecek** [comment]
1 1

**Comment by ViktorStiskala** [comment]
1 1

**Comment by Naomak** [comment]
Dekuji vsem za nazor.
Front: celkem presvedcive - 1
Back: Uz pomerne vyrovnane, ale nakonec 10:6 pro 1 (had)

**Comment by tricoder42** [comment]
:+1:

**Comment by tricoder42** [comment]
Done, ordered, thx @Naomak
