### ISSUE TITLE
[SWAG] Badges

### ISSUE THREAD

**Issue by Naomak** [pyvec/cz.pycon.org-2015#60]
I thought we also could have some badges (placky se zicherkou). We could choose more then one option:
![placky](https://cloud.githubusercontent.com/assets/809507/10179170/98dd91f0-6704-11e5-9469-29ea3e8f4550.png)

**Comment by tricoder42** [comment]
I like (2). (3) would be my second choice.

Nicely done!

**Comment by encukou** [comment]
My vote: 3

Do the 1 & 2 designs appear on some other pycon.cz materials?

**Comment by veruu** [comment]
I like 3 and 4. The first two look a bit creepy to me

**Comment by Naomak** [comment]
@encukou Nope, it was freely inspired by those snakes on python.cz. Although, possibly on t-shirts and we could make some stickers.

**Comment by tricoder42** [comment]
Ordered, thank you @Naomak
