### ISSUE TITLE
New website

### ISSUE THREAD

**Issue by tricoder42** [pyvec/cz.pycon.org-2015#61]
Speakers are going to be announced soon and we need to update website. We should also include lot of other information like venue locations, how to get to Brno, final schedule, etc.
## Proposed structure:
- 1. About
  - Event - general info
  - Tickets - ti.to widget, info what's included in ticker price
  - Speakers - speakers bio, photo, contact info
  - Code of Conduct
  - Sponsorship - sponsorship offers
  - Team - team members and contact info
- 2. Getting here
  - Transport - how to get to Brno by plane, train, bus
  - Venue - where are the venues and how to get there
- 3. Talks / 4. Sprints (two sections but with the same structure)
  - Schedule - daily schedule with short info about talk. Linked to 1/Speakers section.
  - Directions - the most important info how to get to venue (extracted from 2/Venue)
## UX

The default page should depend on day, when website is visited.
1. Before conference - Default page is `Getting here`
2. On Saturday 14th November the default page is `Talks` and day after `Sprints`
3. After conference the new default page will be added with photos and videos.

The main menu remains the same, so user can navigate to any info they need.
### 1. Variant - Static

Keep static website written in `jade`.

Pros:
- easy setup (it's already there)

Cons:
- we're hitting the limits of static website. There is going to be 4-5 main pages linked in between.
### 2. Variant - React & Node

Create simple React app with server-side rendering in Node.

Pros:
- better UX - faster browsing and still search engines can cache static markup.

Cons:
- new setup (both frontend and backend)
### 3. Variant - Flask app

Create simple app in Flask (Django is too heavy in this case)

Pros:
- more people are familiar with Python/Flask - easier to contribute

Cons:
- new setup (both backend and backend)

**Comment by honzajavorek** [comment]
Hybrid variant in case nothing much dynamic is needed - Flask-powered site with http://pythonhosted.org/Frozen-Flask/, hosted statically.

**Comment by tricoder42** [comment]
Dev version available here https://dev.cz.pycon.org/2015/
