### ISSUE TITLE
Add sprint information

### ISSUE THREAD

**Issue by encukou** [pyvec/cz.pycon.org-2015#65]
The "Sprints & Workshops" page currently only has workshops (despite the name).
Please add a "Sprints" section like this:
## Sprints

All day is open for you to sprint on any interesting project. Sprints will be announced after lightning talks on Saturday. If you want your sprint listed here before then, just e-mail the organizers.
### Python 3 Porting

Make your project Python 3 compatible, or help a project you like! Experienced porters can help you on your way, with guidance on porting strategies, pest practices, libraries and automation, or even convincing management/upstream that supporting Python 3 is a good idea.

**Comment by tricoder42** [comment]
Already merged to master. Thx!
