### ISSUE TITLE
Language of talks

### ISSUE THREAD

**Issue by tricoder42** [pyvec/cz.pycon.org-2015#7]
This might depend on #6. If we decide to organize two tracks, one could be for beginners in Czech, the other in English to everyone.

I would vote for :gb: (the main track) so we can either attract more foreign speakers/attendees and publish all videos in english.

**Comment by honzajavorek** [comment]
I vote for Traditional English :gb:, in exceptional cases I'd allow also Simplified English :us:, but that's it.

**Comment by tricoder42** [comment]
:+1: :gb: :us:
