### ISSUE TITLE
Topic of talks

### ISSUE THREAD

**Issue by tricoder42** [pyvec/cz.pycon.org-2015#8]
We can either:
- :one: Select a specific topic for majority of talks
- :two: Leave it completely on speakers

I would vote for :one: in case we have two tracks (see #6).

Possible topics are:
- Python in Education (ping @kvbik)
- Python for hardware (ping @encukou)
- Python in Science (ping @verosK)
- Python for enterprise -- possibly best topic to attract sponsors and show companies how they can use Python…

**Comment by VerosK** [comment]
What about specific track for beginners? Or will be there some talks with "Beginner friendly" badge?

**Comment by tricoder42** [comment]
Depends on number of tracks (see #6). I would like to see one track suitable for beginners, and the other for anyone. If we had just one track, I would go for "Beginner friendly" badge.

**Comment by honzajavorek** [comment]
I vote for not treating beginners as special separate species. A little bit advanced talk about bioinformatics is totally hardcore for me, but would be a boring thing for someone who has basics of bioinformatics. This applies to everything. Beginner web-related talk can be a deep science for someone who works on counting statics of dam water plants in IPython notebooks for half of his life.

Thus I'd like the talks to be mixed and I'd like them to be marked with badge **relative to the topic itself**. E.g. this is beginner talk for those who know web, this is advanced talk for those who know PyQt, etc.

**Comment by encukou** [comment]
I don't think having one topic for the entire conference is a good idea -- a lot of people would be bored, and a lot would not be interested. Let's have talks from all of these topics!

As for the beginner/advanced idea -- if we can pull off having two talks for each topic, one for beginners (in that topic) and one advanced, we could do two tracks.
