### ISSUE TITLE
Call for papers

### ISSUE THREAD

**Issue by tricoder42** [pyvec/cz.pycon.org-2015#9]
Two variants:
- :one: find speakers by ourselves
- :two: let people to sign up on their own
- :three: combine both (find speakers but leave few slots free)
## One

It's a first year, so I would like to find and persuade speakers to attend our conference. Especially when we select specific topic in #8 
## Two

A bit risky, but it's an option.

Personally, I vote for :one:

**Comment by honzajavorek** [comment]
I vote for :three:. Ask speakers themselves and leave also some slots open. I'd also try to encourage some people new to speaking or to Python itself to have a talk. Maybe lightning talk slots?

**Comment by encukou** [comment]
I also vote for 3. If we do a good job, people should be asking us if they can speak :)

I'd love to have lightning talks. We should encourage everyone who plans to come to think about a lightning talk, ahead of time.

**Comment by ricco386** [comment]
I think :three: is good idea. 

Invite people, that the line up is interesting is important. But give also a chance to people who would like to start speaking at conferences or doesn’t have many talks behind them... I think it would be great encouragement for people and also great experience for them. Ration between invited people and people volunteered to speak doesn’t have to be half:half but I think there should be at least some space. At the end of the day you will see how many people volunteered and if you ask for speech content you will also see it it fits into the concept, and you don’t have to accept every speech...

**Comment by tricoder42** [comment]
Alright, let's go with :three: 

Thank you!
